# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
