# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_qtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
