# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-17 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20191216_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='uppers',
            field=models.ManyToManyField(related_name='upped', to=settings.AUTH_USER_MODEL),
        ),
    ]
