# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prereq', models.ManyToManyField(blank=True, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
                ('registered', models.ManyToManyField(related_name='enrolled', to='student.Course')),
                ('took', models.ManyToManyField(related_name='taken', to='student.Course')),
            ],
        ),
    ]
