# Generated by Django 2.2.24 on 2021-12-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
